INSERT INTO USER_CREDENTIAL
(EMAIL, PASSWORD, AUTHORITY, BIRTH_DATE, STREET, ZIP_CODE, CITY, COUNTRY)
VALUES (
  'test1@test.com',
  '$2a$10$fx3DJpvpCo2QtrNMv5Rkp.H9FCToWzKDUgyCsy1Ugi9AmmM/U4doS',
  'ROLE_USER',
  '1980-01-01',
  'test',
  'test',
  'test',
  'BELGIUM');

--INSERT INTO USER_CREDENTIAL (PASSWORD) VALUES ('$2a$10$fx3DJpvpCo2QtrNMv5Rkp.H9FCToWzKDUgyCsy1Ugi9AmmM/U4doS');
--INSERT INTO USER_CREDENTIAL (EMAIL) VALUES ('test@test.com');
--INSERT INTO USER_CREDENTIAL (AUTHORITY) VALUES ('ROLE_USER');
-- INSERT INTO USER_CREDENTIAL (BIRTH_DATE) VALUES ('1980-01-01 Food');
-- INSERT INTO USER_CREDENTIAL (STREET) VALUES ('test');
-- INSERT INTO USER_CREDENTIAL (ZIP_CODE) VALUES ('test');
-- INSERT INTO USER_CREDENTIAL (CITY) VALUES ('test');
-- INSERT INTO USER_CREDENTIAL (COUNTRY) VALUES ('BELGIUM');
